apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pathfinder
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    impactedControls: [x001, x002, x003]
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
  
